default:
  image: python:3.9
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build twine

stages:
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

build:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  environment:
    name: release
  script:
    - TWINE_PASSWORD=${TWINE_PASSWORD} TWINE_USERNAME=${TWINE_USERNAME} python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --verbose
  rules:
    - if: $CI_COMMIT_TAG